export const TAG_MAP = new Map([
  ['fate', 'Fate/GrandOrder'],
  ['fgo', 'Fate/GrandOrder'],
  ['ask', 'ASK'],
  ['玛修', 'マシュ・キリエライト'],
  ['马修', 'マシュ・キリエライト'],
  ['マシュ', 'マシュ・キリエライト'],
  ['所罗门', 'ソロモン'],
  ['ソロモン', 'ソロモン'],
  ['命运冠位指定', 'Fate/GrandOrder'],
  ['fatego', 'Fate/GrandOrder'],
  ['fate grand order', 'Fate/GrandOrder'],
  ['fgo200000users入り', 'Fate/GO200000users入り'],
  ['逆光', '逆光'],
  ['笑容', '最高の笑顔'],
  ['beautiful', 'なにこれ綺麗'],
  ['fgo/fate/grandorder', 'FGO/Fate/GrandOrder'],
  ['fate grandorder', 'Fate/GrandOrder'],
  ['命运·冠位指定', 'Fate/GrandOrder/命运・冠位指定'],
  ['太美了', '素晴らしすぎる'],
  ['wtf this is beautiful', 'なにこれ綺麗'],
  ['the perfect smile', '最高の笑顔'],
  ['冠位时间神殿所罗门', '冠位時間神殿ソロモン'],
  ['冠位時間神殿ソロモン', '冠位時間神殿ソロモン'],
  ['永远的色彩', '逆光に浮かぶ永遠の色彩'],
  ['genshin', '原神'],
  ['原神', '原神'],
  ['hatsune miku', '初音ミク'],
  ['miku', '初音ミク'],
  ['初音', '初音ミク'],
  ['原创', 'オリジナル'],
  ['original', 'オリジナル'],
  ['风景', '風景'],
  ['landscape', '風景'],
  ['白发', '白髪'],
  ['白髪', '白髪'],
  ['jk', '制服'],
  ['制服', '制服'],
  ['泳装', '水着'],
  ['swimsuit', '水着'],
  ['偶像', 'アイドル'],
  ['idol', 'アイドル'],
  ['猫娘', '猫耳'],
  ['女仆', 'メイド'],
  ['机甲', 'メカ'],
  ['科幻', 'SF'],
  ['赛博朋克', 'サイバーパンク'],
  ['狐娘', '狐耳'],
  ['碧蓝航线', 'アズールレーン'],
  ['明日方舟', 'アークナイツ'],
]);

export function normalizeTag(input) {
  const raw = String(input || '').trim();
  if (!raw) return '';
  const lower = raw.toLowerCase();
  return TAG_MAP.get(lower) || TAG_MAP.get(raw) || raw;
}
